In [1]:
import numpy as np

# Fiche 1

# EXERCICE 1

In [29]:
scalaire_1=np.array(5)
scalaire_2=np.array(6)
print(scalaire_1 + scalaire_2)

11


# EXERCICE 2

In [10]:
vecteur_1=np.array([1,2,3])
vecteur_2=np.array([3,2,1])
vecteur_3=np.array([0,1,-1])
vecteurs=vecteur_1+vecteur_2+vecteur_3
print(vecteurs)
print(vecteurs.shape)

[4 5 3]
(3,)


# EXERCICE 3

In [30]:
scalaire=np.array(0)
vecteur=np.array([125,2185,321,665,17,-8])
resultat=scalaire*vecteur
print(resultat)

[0 0 0 0 0 0]


# EXERCICE 4

In [15]:
matrice=np.array([[1,2,3],[4,5,6]])
matrice.shape

(2, 3)

# EXERCICE 5

In [18]:
matrice_1=np.array([[1,2,3,4],[5,6,7,8]])
matrice_2=np.array([[2,2,2,2],[1,1,1,1]])
resultat=matrice_1 + matrice_2
print(resultat)

[[3 4 5 6]
 [6 7 8 9]]


# EXERCICE 6

In [27]:
V1=np.array([4,7])
V2=np.array([3,6])
a1=2
a2=3
a3=1.5
vect1=V1*a1
print(vect1)
vect2=V2*a2
print(vect2)
vect3=vect1 + vect2
print(vect3)
vect4=vect3*a3
print(vect4)

[ 8 14]
[ 9 18]
[17 32]
[25.5 48. ]


In [41]:
matrice=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]])
matrice

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
matrice[0:1]=0

In [43]:
matrice

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Fiche 2

# EXERCICE 1

In [44]:
matrice=np.array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30],
    [31,32,33,34,35,36,37,38,39,40],
    [41,42,43,44,45,46,47,48,48,50]
])

In [45]:
matrice[3:,5:]

array([[36, 37, 38, 39, 40],
       [46, 47, 48, 48, 50]])

In [46]:
matrice[-1,-1]

50

In [47]:
matrice[-2:,6:]

array([[37, 38, 39, 40],
       [47, 48, 48, 50]])